require("config.keymaps")
require("setup.bootstraplazy")
require("lazy").setup(require("pluginloader"))
--require("plugins.whichkey.setup")
require("mason").setup()
require("mason-lspconfig").setup()
require("config.settings")
--require("lazy").setup({{"nvim-treesitter/nvim-treesitter", build = ":TSUpdate"}})
require("config.lsp")
require("plugins.cmp.config")
require("plugins.lspconfig.config")
require("plugins.bufferline.config")
require("lspsetup")
